# Generated by Django 4.1.7 on 2023-03-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null='true')),
                ('email', models.EmailField(max_length=100, null='true')),
                ('password', models.CharField(max_length=128, null='true')),
                ('contact_number', models.CharField(max_length=15, null='true')),
                ('date_of_birth', models.DateField(null='true')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null='true')),
                ('designation', models.CharField(max_length=100, null='true')),
                ('department', models.CharField(max_length=100, null='true')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100, null='true')),
                ('institute_name', models.CharField(max_length=100, null='true')),
                ('passing_year', models.IntegerField(null='true')),
                ('percentage', models.FloatField(null='true')),
                ('employee', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='adminapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(null='true', upload_to='certificates/')),
                ('employee', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='adminapp.employee')),
            ],
        ),
    ]
