# Generated by Django 4.1.7 on 2023-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null='true')),
                ('task', models.CharField(max_length=255, null='true')),
            ],
        ),
    ]
