# Generated by Django 4.1.7 on 2023-03-09 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_dailyupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdate',
            name='employee',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='adminapp.employee'),
            preserve_default='true',
        ),
    ]
